[versions]
kotlin = "2.0.0"
shadow = "8.1.1"
grpc-version = "1.61.0"
grpc-kotlin-version = "1.4.1"
simplecloud-controller = "0.0.30-dev.95b1794"
# implementation("org.incendo:cloud-paper:2.0.0-beta.8")
paper = "1.21.1-R0.1-SNAPSHOT"
cloud-commands = "2.0.0-beta.10"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-version" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin-version" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-version" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-commands" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-commands" }

simplecloud-controller-api = { module = "app.simplecloud.controller:controller-api", version.ref = "simplecloud-controller" }
simplecloud-controller-shared = { module = "app.simplecloud.controller:controller-shared", version.ref = "simplecloud-controller" }

[bundles]
simplecloud-controller = ["simplecloud-controller-api", "simplecloud-controller-shared"]
cloud-paper = ["cloud-paper", "cloud-minecraft-extras"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
