name: SimpleCloud-Signs
version: 1.0
author: Fllip
description: A simple plugin that adds signs to SimpleCloud
main: app.simplecloud.plugin.sign.paper.PaperSignsPlugin
api-version: "1.21.1"
bootstrapper: app.simplecloud.plugin.sign.paper.PaperSignsPluginBootstrap